name: abapLint

on: 
  push:
    paths: '/src/**.abap'
    branches:
      - master

jobs:
  abapLint:
    runs-on: ubuntu-latest
    steps:
      - name: abapLint
        uses: abaplint/actions-abaplint@master
        env: 
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}  
