name: abapLint
  
on: 
  push:
    paths: '/src/**'
    branches: 
      - master
  pull_request:
    paths: '/src/**'
    branches:
      - master

jobs:
  abapLint:
    runs-on: ubuntu-latest
    steps:
      - name: abapLint
        uses: abaplint/actions-abaplint@master
        env: 
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
