name: abapLint
  
on: 
  push:
    paths: '/src/**.abap'
  pull_request:
    paths: '/src/**.abap'

jobs:
  abapLint:
    runs-on: ubuntu-latest
    steps:
      - name: abapLint
        uses: abaplint/actions-abaplint@master
        env: 
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
