name: abapLint

on:
 push:
    branches: [ master ]
    paths: '/src/**.abap'

jobs:
  abapLint:
    runs-on: ubuntu-latest
    steps:
      - name: abapLint
        uses: abaplint/actions-abaplint@master
        env: 
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}  
