name: abapLint

on:
 push:
    branches: [ master ]
    paths: '/src/**.abap'

jobs:
  abapLint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: abapLint
       uses: abaplint/actions-abaplint@master
       env: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
